name: Build (Api Gateway)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Restore node_modules from cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install dependencies
      run: npm install
    - name: Run build task
      run: npm run build
      env:
        # Testing Environment (Without firewall)
        FILE_SERVICE_URL: "http://143.244.204.177"
        AUTH_SERVICE_URL: "http://165.232.72.179"
        MAIN_API_SERVICE_URL: "http://174.138.102.12"
