name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - run: npm run lint --if-present
    - run: npm test
      env:
        # Testing Environments
        FILE_SERVICE_URL: http://143.244.204.177
        AUTH_SERVICE_URL: http://165.232.72.179
        MAIN_API_SERVICE_URL: http://174.138.102.12
    - run: npm run build --if-present
      env:
        CI: true

