name: Node.js CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn test
        env:
          FILE_SERVICE_URL: "http://143.244.204.177"
          AUTH_SERVICE_URL: "http://165.232.72.179"
          MAIN_API_SERVICE_URL: "http://174.138.102.12"
